linters:
  enable:
    - dupl
    - durationcheck
    - errname
    - gocritic
    - goimports
    - gosec
    - nakedret
    - nilerr
    - nilnil
    - revive
    - stylecheck
    - unconvert
    - unparam
